### ISSUE TITLE
Create readme.md

### ISSUE THREAD

**Issue by thisisshub** [thisisshub/website-updated#1]
Every project / website / software needs a readme to understand what it does or how it works. So does our website. Read the code and create a `readme.md` using a markdown editor.

**Comment by flux0806** [comment]
[readme.md.txt](https://github.com/thisisshub/website-updated/files/3768540/readme.md.txt)

This is the code for a Shopping Application. Here the user can choose between Platinum, Gold and Silver Membership cards and get an appropriate discount.
